#PATHS
test_data_path='../test_data_vector/'
input_data_path=test_data_path+'input/'
output_data_path=test_data_path+'output/'
western_australia=input_data_path+'500k_interpgeop16_info_clip.shp'
geology_file=input_data_path+'500K_interpgeol16_yalgoo_singleton_info.shp'
geology_file2=input_data_path+'500K_interpgeol16_yalgoo_singleton2.shp'

aggregate_file=output_data_path+'500K_interpgeol16_yalgoo_singleton_aggregate.shp'
simplified_file=output_data_path+'500K_interpgeol16_yalgoo_singleton_simplify_1100.shp'

simplified_file_a=output_data_path+'500K_interpgeol16_yalgoo_singleton_simplify_a.shp'
simplified_file_b=output_data_path+'500K_interpgeol16_yalgoo_singleton_simplify_b.shp'
simplified_file_c=output_data_path+'500K_interpgeol16_yalgoo_singleton_simplify_c.shp'
simplified_file_d=output_data_path+'500K_interpgeol16_yalgoo_singleton_simplify_d.shp'

simplified_points_a=output_data_path+'500K_interpgeol16_yalgoo_singleton_points_a.shp'
simplified_points_b=output_data_path+'500K_interpgeol16_yalgoo_singleton_points_b.shp'
simplified_points_c=output_data_path+'500K_interpgeol16_yalgoo_singleton_points_c.shp'

#<img src='../graphics/map_sm.png'>